### ISSUE TITLE
Add a toggle to display/hide the action buttons on attendees for cohosts

### ISSUE THREAD

**Issue by akirk** [WordPress/wporg-gp-translation-events#219]
The many "Make cohost" buttons are a bit overwhelming.

![Screenshot 2024-04-17 at 14 18 53](https://github.com/WordPress/wporg-gp-translation-events/assets/203408/c47439ce-5cab-47e3-b13f-74262e75c098)

**Comment by psrpinto** [comment]
I think an alternative option would be to add the add/remove host buttons to the event edit screen instead of the event details screeen.

**Comment by psrpinto** [comment]
I think managing hosts could be seen as editing the event, so it could make sense to instead manage hosts through the edit page, instead of through the event details page.

In addition, instead of displaying "Make co-host" and "Remove co-host" buttons for every attendee, managing hosts could be done through a different UI. An example is described as follows.

In the edit event page we could show the list of hosts as `<ul>`, with a "Remove as host" button next to each host. To add hosts, we could have a `<select>` with the list of attendees with a "Make co-host" button next to it.

This would address both issues:

1. Declutter the event details page for users who are a host of the event
2. Move managing hosts to the edit page. This would mean managing hosts would also automatically get the capabilities checks that are done on the edit event page (related: #215 ).
