### ISSUE TITLE
Update header and footer designs

### ISSUE THREAD

**Issue by trymebytes** [WordPress/wporg-gp-translation-events#286]
See Figma designs here https://www.figma.com/design/Q3RpUkAJhTaKVmXdGGJIBs/Translating-WordPress?node-id=41-950 for guidance.

**Comment by akirk** [comment]
I'd advise that we'll investigate whether we can use the existing global-header as it's seen on https://events.wordpress.org/ but am not sure whether it's going to be helpful or need customization so that adapting it takes a lot of time. We need to assess that first.

The idea of new themes on WordPress.org are to be Block Themes that use version control. This means that the page layout can be used using "traditional php" which serves us well in the GlotPress environment but using blocks that are invoked using `do_blocks`.

For example, the Global Header would be rendered using this PHP:
```php
echo do_blocks( '<!-- wp:wporg/global-footer /-->' );
```

For this to work locally, it is important to have a setup like WordPress.org, for that I recommend to use https://github.com/WordPress/translate-w-org-env/
