### ISSUE TITLE
test_get_past_events_for_user is flaky

### ISSUE THREAD

**Issue by akirk** [WordPress/wporg-gp-translation-events#308]
It failed here: https://github.com/WordPress/wporg-gp-translation-events/actions/runs/9268332809/job/25496731899
![Screenshot 2024-05-28 at 13 22 21](https://github.com/WordPress/wporg-gp-translation-events/assets/203408/4bfe5a2a-92ea-4930-91b2-4fe7d7518397)

And worked on the re-run: https://github.com/WordPress/wporg-gp-translation-events/actions/runs/9268332809/job/25496794775

**Comment by amieiro** [comment]
We tried to resolve this bug in https://github.com/WordPress/wporg-gp-translation-events/pull/294, but it didn't work. We have the same random behavior than before.

**Comment by psrpinto** [comment]
I think the problem is that "now" [is instantiated in the code under test](https://github.com/WordPress/wporg-gp-translation-events/blob/trunk/includes/event/event-repository.php#L305), so the test probably fails when "now" ends up being in the next second.

This is actually not a simple problem to solve, I think we'd need to look into strategies for faking "now" when testing.

**Comment by akirk** [comment]
Interesting! I don't think it's too hard to solve, though. We can just do something similar to dependency injection just for the `$now`, no?

**Comment by akirk** [comment]
We should ensure to just create a single `$now` timestamp at the start of the test and then create all times as a modification of that original time. For example, instead of
```
		$start    = new Event_Start_Date( 'now' );
		$end      = new Event_End_Date( 'now' );
```
we do
```
		$start    = new Event_Start_Date( $this->now );
		$end      = new Event_End_Date( $this->now );
```

**Comment by psrpinto** [comment]
Injecting the `$now` would fix it indeed, good point.
