### ISSUE TITLE
Hide the Manage Attendees button if it is not permitted for the user

### ISSUE THREAD

**Issue by akirk** [WordPress/wporg-gp-translation-events#317]
Clicking on Manage Attendees for an event I didn't create but I can edit (I suppose because of Admin on the site)

![Screenshot 2024-06-04 at 11 21 54](https://github.com/WordPress/wporg-gp-translation-events/assets/203408/950151c6-51a5-463f-b0d8-fe9580ea84ba)

gives me
![Screenshot 2024-06-04 at 11 21 59](https://github.com/WordPress/wporg-gp-translation-events/assets/203408/77e548c3-edab-4054-b068-3aabec6a6884)

**Comment by trymebytes** [comment]
The reason for this is because the `edit_translation_event_attendees` cap check is missing [here](https://github.com/WordPress/wporg-gp-translation-events/blob/cb4089d6ab35a1fed76bf45742f64b7242b69cae/templates/event-edit.php#L30). However, we introduced the `edit_translation_event_attendees` cap to fix #242 . 
Since we introduced the `edit_translation_event_title` and other similar capabilities for form fields, I believe we no longer need the `edit_translation_event_attendees` cap and we can make use of the `edit_translation_event`  cap check to check if a user can edit attendees.

Therefore if a user can  access the edit form, they should be able to edit the event attendees.
